/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        WordChoser wordChoser = new WordChoser();
        Masker masker = new Masker();
        Game game = new Game(wordChoser, masker, "Samuel");
        System.out.println("Welcome! Today the word to guess is: ");

        do {
            System.out.println(game.getWordToGuess());
            System.out.println("Enter one letter to guess (" + game.getRemainingAttempts() + " attempts remaining): ");

            Scanner scanner = new Scanner(System.in);
            Character letter = scanner.nextLine().charAt(0);

            if (game.guessLetter(letter)) {
                System.out.println("Right!");

                if (game.isGameWon()) {
                    System.out.println("The word is: " + game.getWordToGuess());
                    System.out.println("Congratulations! You won the game.");
                    break;
                }
            } else {
                System.out.println("Wrong!");
            }
        } while(!game.isGameLost());
    }
}
